# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger: none

# YAML file in the main branch
schedules:
- cron: '5 0 * * *'
  displayName: Daily midnight run (8pm EDT)
  branches:
    include:
    - main
- cron: '5 12 * * *'
  displayName: Daily noon run (8am EDT)
  branches:
    include:
    - main
- cron: '5 12 * * *'
  displayName: Daily 6pm run (2pm EDT)
  branches:
    include:
    - main


pool:
  vmImage: ubuntu-latest

parameters:
  - name: will_it_skeet
    default: True

variables:
- group: "Rogue_NHC_Atlantic_Bluesky"
# - name: BLUESKY_USER
#   value: $[variables.user]
# - name: BLUESKY_PASS
#   value: $[variables.password]
# - name: WILL_SKEET
#   value: $(will_it_skeet)

steps:
# - script: |
#     echo $BLUESKY_USER
#     echo $BLUESKY_PASS
- script: pip3 install -U atproto
  displayName: pip install
- script: ./main.py
  displayName: run main.py
  env:
    BLUESKY_USER: $(user)
    BLUESKY_PASS: $(password)
    WILL_SKEET: ${{ parameters.will_it_skeet }}
