trigger: none

# YAML file in the main branch
schedules:
- cron: '5 0 * * *'
  displayName: Daily midnight run (8pm EDT)
  branches:
    include:
    - main
  always: true
- cron: '5 12 * * *'
  displayName: Daily noon run (8am EDT)
  branches:
    include:
    - main
  always: true
- cron: '5 18 * * *'
  displayName: Daily 6pm run (2pm EDT)
  branches:
    include:
    - main
  always: true


pool:
  vmImage: ubuntu-latest

parameters:
  - name: will_it_skeet
    default: False

jobs:
- job: Atlantic
  variables:
  - group: "Rogue_NHC_Atlantic_Bluesky"
  steps:
  # - script: |
  #     echo $BLUESKY_USER
  #     echo $BLUESKY_PASS
  - script: pip3 install -U atproto
    displayName: pip install
  - script: ./main.py
    displayName: run main.py
    env:
      BLUESKY_USER: $(user)
      BLUESKY_PASS: $(password)
      WILL_SKEET: ${{ parameters.will_it_skeet }}
