# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: "Rogue_NHC_Atlantic_Bluesky"
# - name: BLUESKY_USER
#   value: $[variables.user]
# - name: BLUESKY_PASS
#   value: $[variables.password]

steps:
# - script: |
#     echo $BLUESKY_USER
#     echo $BLUESKY_PASS
- script: pip3 install -U atproto
  displayName: pip install
- script: ./main.py
  displayName: run main.py
  env:
    BLUESKY_USER: $(user)
    BLUESKY_PASS: $(password)
